import { App } from './app.model';

export const EDITORSCHOICEAPPS: App[] = [
  {
    "flatpakAppId": "org.kde.kdenlive",
    "name": "Kdenlive",
    "summary": "Video Editor",
    description: '',
    projectLicense: '',
    "iconDesktopUrl": "/repo/appstream/x86_64/icons/128x128/org.kde.kdenlive.png",
    "iconMobileUrl": "/repo/appstream/x86_64/icons/64x64/org.kde.kdenlive.png",
    homepageUrl: '',
    bugtrackerUrl: '',
    downloadFlatpakRefUrl: '',
    currentReleaseVersion: '',
    currentReleaseDate: null,
    currentReleaseDescription: '',
    inStoreSinceDate: null,
    screenshots: []
  },
  {
    flatpakAppId: "org.gimp.GIMP",
    name: "GNU Image Manipulation Program",
    summary: "Create images and edit photographs",
    description: '',
    projectLicense: '',
    iconDesktopUrl: "/repo/appstream/x86_64/icons/128x128/org.gimp.GIMP.png",
    iconMobileUrl: "/repo/appstream/x86_64/icons/64x64/org.gimp.GIMP.png",
    homepageUrl: '',
    bugtrackerUrl: '',
    downloadFlatpakRefUrl: '',
    currentReleaseVersion: '',
    currentReleaseDate: null,
    currentReleaseDescription: '',
    inStoreSinceDate: null,
    screenshots: []
  },
  {
    flatpakAppId: "com.slack.Slack",
    name: "Slack",
    summary: "Chat with your team",
    description: '',
    projectLicense: '',
    iconDesktopUrl: "https://lh3.googleusercontent.com/Dq-mZ5mmdE6aFPeD61DNlVTwYSI75UwHBYDq_BxBZOMSzCBnQ5OCC4-LjfP42tDlyw=w128",
    iconMobileUrl: "https://lh3.googleusercontent.com/Dq-mZ5mmdE6aFPeD61DNlVTwYSI75UwHBYDq_BxBZOMSzCBnQ5OCC4-LjfP42tDlyw=w128",
    homepageUrl: '',
    bugtrackerUrl: '',
    downloadFlatpakRefUrl: '',
    currentReleaseVersion: '',
    currentReleaseDate: null,
    currentReleaseDescription: '',
    inStoreSinceDate: null,
    screenshots: []
  },
  {
    flatpakAppId: "com.visualstudio.code",
    name: "Visual Studio Code",
    summary: "Visual Studio Code. Code editing. Redefined.",
    description: '',
    projectLicense: '',
    iconDesktopUrl: "/repo/appstream/x86_64/icons/128x128/com.visualstudio.code.png",
    iconMobileUrl: "/repo/appstream/x86_64/icons/64x64/com.visualstudio.code.png",
    homepageUrl: '',
    bugtrackerUrl: '',
    downloadFlatpakRefUrl: '',
    currentReleaseVersion: '',
    currentReleaseDate: null,
    currentReleaseDescription: '',
    inStoreSinceDate: null,
    screenshots: []
  },
  {
    flatpakAppId: "com.spotify.Client",
    name: "Spotify",
    summary: "Online music streaming service",
    description: '',
    projectLicense: '',
    iconDesktopUrl: "https://lh3.googleusercontent.com/UrY7BAZ-XfXGpfkeWg0zCCeo-7ras4DCoRalC_WXXWTK9q5b0Iw7B0YQMsVxZaNB7DM=w128",
    iconMobileUrl: "https://lh3.googleusercontent.com/UrY7BAZ-XfXGpfkeWg0zCCeo-7ras4DCoRalC_WXXWTK9q5b0Iw7B0YQMsVxZaNB7DM=w128",
    homepageUrl: '',
    bugtrackerUrl: '',
    downloadFlatpakRefUrl: '',
    currentReleaseVersion: '',
    currentReleaseDate: null,
    currentReleaseDescription: '',
    inStoreSinceDate: null,
    screenshots: []
  },
  {
    "flatpakAppId": "org.videolan.VLC",
    "name": "VLC",
    "summary": "VLC media player, the open-source multimedia player",
    description: '',
    projectLicense: '',
    "iconDesktopUrl": "/repo/appstream/x86_64/icons/128x128/org.videolan.VLC.png",
    "iconMobileUrl": "/repo/appstream/x86_64/icons/64x64/org.videolan.VLC.png",
    homepageUrl: '',
    bugtrackerUrl: '',
    downloadFlatpakRefUrl: '',
    currentReleaseVersion: '',
    currentReleaseDate: null,
    currentReleaseDescription: '',
    inStoreSinceDate: null,
    screenshots: []
  },
  {
    "flatpakAppId": "com.google.AndroidStudio",
    "name": "Android Studio",
    "summary": "Integrated development environment for Google's Android platform",
    description: '',
    projectLicense: '',
    "iconDesktopUrl": "/repo/appstream/x86_64/icons/128x128/com.google.AndroidStudio.png",
    "iconMobileUrl": "/repo/appstream/x86_64/icons/64x64/com.google.AndroidStudio.png",
    homepageUrl: '',
    bugtrackerUrl: '',
    downloadFlatpakRefUrl: '',
    currentReleaseVersion: '',
    currentReleaseDate: null,
    currentReleaseDescription: '',
    inStoreSinceDate: null,
    screenshots: []
  },
  {
    "flatpakAppId": "org.gnome.Lollypop",
    "name": "Lollypop",
    "summary": "Play and organize your music collection",
    description: '',
    projectLicense: '',
    "iconDesktopUrl": "/repo/appstream/x86_64/icons/128x128/org.gnome.Lollypop.png",
    "iconMobileUrl": "/repo/appstream/x86_64/icons/64x64/org.gnome.Lollypop.png",
    homepageUrl: '',
    bugtrackerUrl: '',
    downloadFlatpakRefUrl: '',
    currentReleaseVersion: '',
    currentReleaseDate: null,
    currentReleaseDescription: '',
    inStoreSinceDate: null,
    screenshots: []
  },
];
