import { App } from './app.model';

export const EMPTYAPPS: App[] = [
  {
    flatpakAppId: '',
    name: '',
    summary: '',
    description: '',
    projectLicense: '',
    iconUrl: '',
    homepageUrl: '',
    bugtrackerUrl: '',
    downloadFlatpakRefUrl: '',
    currentRelease: '',
    screenshots:[]
  },
  {
    flatpakAppId: '',
    name: '',
    summary: '',
    description: '',
    projectLicense: '',
    iconUrl: '',
    homepageUrl: '',
    bugtrackerUrl: '',
    downloadFlatpakRefUrl: '',
    currentRelease: '',
    screenshots:[]
  },
  {
    flatpakAppId: '',
    name: '',
    summary: '',
    description: '',
    projectLicense: '',
    iconUrl: '',
    homepageUrl: '',
    bugtrackerUrl: '',
    downloadFlatpakRefUrl: '',
    currentRelease: '',
    screenshots:[]
  },
  {
    flatpakAppId: '',
    name: '',
    summary: '',
    description: '',
    projectLicense: '',
    iconUrl: '',
    homepageUrl: '',
    bugtrackerUrl: '',
    downloadFlatpakRefUrl: '',
    currentRelease: '',
    screenshots:[]
  },
  {
    flatpakAppId: '',
    name: '',
    summary: '',
    description: '',
    projectLicense: '',
    iconUrl: '',
    homepageUrl: '',
    bugtrackerUrl: '',
    downloadFlatpakRefUrl: '',
    currentRelease: '',
    screenshots:[]
  },
  {
    flatpakAppId: '',
    name: '',
    summary: '',
    description: '',
    projectLicense: '',
    iconUrl: '',
    homepageUrl: '',
    bugtrackerUrl: '',
    downloadFlatpakRefUrl: '',
    currentRelease: '',
    screenshots:[]
  },
  {
    flatpakAppId: '',
    name: '',
    summary: '',
    description: '',
    projectLicense: '',
    iconUrl: '',
    homepageUrl: '',
    bugtrackerUrl: '',
    downloadFlatpakRefUrl: '',
    currentRelease: '',
    screenshots:[]
  },
  {
    flatpakAppId: '',
    name: '',
    summary: '',
    description: '',
    projectLicense: '',
    iconUrl: '',
    homepageUrl: '',
    bugtrackerUrl: '',
    downloadFlatpakRefUrl: '',
    currentRelease: '',
    screenshots:[]
  },
  {
    flatpakAppId: '',
    name: '',
    summary: '',
    description: '',
    projectLicense: '',
    iconUrl: '',
    homepageUrl: '',
    bugtrackerUrl: '',
    downloadFlatpakRefUrl: '',
    currentRelease: '',
    screenshots:[]
  },
  {
    flatpakAppId: '',
    name: '',
    summary: '',
    description: '',
    projectLicense: '',
    iconUrl: '',
    homepageUrl: '',
    bugtrackerUrl: '',
    downloadFlatpakRefUrl: '',
    currentRelease: '',
    screenshots:[]
  },
  {
    flatpakAppId: '',
    name: '',
    summary: '',
    description: '',
    projectLicense: '',
    iconUrl: '',
    homepageUrl: '',
    bugtrackerUrl: '',
    downloadFlatpakRefUrl: '',
    currentRelease: '',
    screenshots:[]
  },
  {
    flatpakAppId: '',
    name: '',
    summary: '',
    description: '',
    projectLicense: '',
    iconUrl: '',
    homepageUrl: '',
    bugtrackerUrl: '',
    downloadFlatpakRefUrl: '',
    currentRelease: '',
    screenshots:[]
  }
];
