import { App } from './app.model';

export const EMPTYAPPS: App[] = [
  {
    flatpakAppId: '',
    name: '',
    summary: '',
    description: '',
    projectLicense: '',
    iconDesktopUrl: '',
    iconMobileUrl: '',
    homepageUrl: '',
    bugtrackerUrl: '',
    downloadFlatpakRefUrl: '',
    currentReleaseVersion: '',
    currentReleaseDate: null,
    currentReleaseDescription: '',
    inStoreSinceDate: null,
    screenshots:[]
  },
  {
    flatpakAppId: '',
    name: '',
    summary: '',
    description: '',
    projectLicense: '',
    iconDesktopUrl: '',
    iconMobileUrl: '',
    homepageUrl: '',
    bugtrackerUrl: '',
    downloadFlatpakRefUrl: '',
    currentReleaseVersion: '',
    currentReleaseDate: null,
    currentReleaseDescription: '',
    inStoreSinceDate: null,
    screenshots:[]
  },
  {
    flatpakAppId: '',
    name: '',
    summary: '',
    description: '',
    projectLicense: '',
    iconDesktopUrl: '',
    iconMobileUrl: '',
    homepageUrl: '',
    bugtrackerUrl: '',
    downloadFlatpakRefUrl: '',
    currentReleaseVersion: '',
    currentReleaseDate: null,
    currentReleaseDescription: '',
    inStoreSinceDate: null,
    screenshots:[]
  },
  {
    flatpakAppId: '',
    name: '',
    summary: '',
    description: '',
    projectLicense: '',
    iconDesktopUrl: '',
    iconMobileUrl: '',
    homepageUrl: '',
    bugtrackerUrl: '',
    downloadFlatpakRefUrl: '',
    currentReleaseVersion: '',
    currentReleaseDate: null,
    currentReleaseDescription: '',
    inStoreSinceDate: null,
    screenshots:[]
  },
  {
    flatpakAppId: '',
    name: '',
    summary: '',
    description: '',
    projectLicense: '',
    iconDesktopUrl: '',
    iconMobileUrl: '',
    homepageUrl: '',
    bugtrackerUrl: '',
    downloadFlatpakRefUrl: '',
    currentReleaseVersion: '',
    currentReleaseDate: null,
    currentReleaseDescription: '',
    inStoreSinceDate: null,
    screenshots:[]
  },
  {
    flatpakAppId: '',
    name: '',
    summary: '',
    description: '',
    projectLicense: '',
    iconDesktopUrl: '',
    iconMobileUrl: '',
    homepageUrl: '',
    bugtrackerUrl: '',
    downloadFlatpakRefUrl: '',
    currentReleaseVersion: '',
    currentReleaseDate: null,
    currentReleaseDescription: '',
    inStoreSinceDate: null,
    screenshots:[]
  },
  {
    flatpakAppId: '',
    name: '',
    summary: '',
    description: '',
    projectLicense: '',
    iconDesktopUrl: '',
    iconMobileUrl: '',
    homepageUrl: '',
    bugtrackerUrl: '',
    downloadFlatpakRefUrl: '',
    currentReleaseVersion: '',
    currentReleaseDate: null,
    currentReleaseDescription: '',
    inStoreSinceDate: null,
    screenshots:[]
  },
  {
    flatpakAppId: '',
    name: '',
    summary: '',
    description: '',
    projectLicense: '',
    iconDesktopUrl: '',
    iconMobileUrl: '',
    homepageUrl: '',
    bugtrackerUrl: '',
    downloadFlatpakRefUrl: '',
    currentReleaseVersion: '',
    currentReleaseDate: null,
    currentReleaseDescription: '',
    inStoreSinceDate: null,
    screenshots:[]
  },
  {
    flatpakAppId: '',
    name: '',
    summary: '',
    description: '',
    projectLicense: '',
    iconDesktopUrl: '',
    iconMobileUrl: '',
    homepageUrl: '',
    bugtrackerUrl: '',
    downloadFlatpakRefUrl: '',
    currentReleaseVersion: '',
    currentReleaseDate: null,
    currentReleaseDescription: '',
    inStoreSinceDate: null,
    screenshots:[]
  },
  {
    flatpakAppId: '',
    name: '',
    summary: '',
    description: '',
    projectLicense: '',
    iconDesktopUrl: '',
    iconMobileUrl: '',
    homepageUrl: '',
    bugtrackerUrl: '',
    downloadFlatpakRefUrl: '',
    currentReleaseVersion: '',
    currentReleaseDate: null,
    currentReleaseDescription: '',
    inStoreSinceDate: null,
    screenshots:[]
  },
  {
    flatpakAppId: '',
    name: '',
    summary: '',
    description: '',
    projectLicense: '',
    iconDesktopUrl: '',
    iconMobileUrl: '',
    homepageUrl: '',
    bugtrackerUrl: '',
    downloadFlatpakRefUrl: '',
    currentReleaseVersion: '',
    currentReleaseDate: null,
    currentReleaseDescription: '',
    inStoreSinceDate: null,
    screenshots:[]
  },
  {
    flatpakAppId: '',
    name: '',
    summary: '',
    description: '',
    projectLicense: '',
    iconDesktopUrl: '',
    iconMobileUrl: '',
    homepageUrl: '',
    bugtrackerUrl: '',
    downloadFlatpakRefUrl: '',
    currentReleaseVersion: '',
    currentReleaseDate: null,
    currentReleaseDescription: '',
    inStoreSinceDate: null,
    screenshots:[]
  }
];
