import { Review } from './review.model';

export const REVIEWS: Review[] = [
  {
    "app_id": "org.gnome.gedit.desktop",
    "date_created": 1478795967,
    "date_deleted": null,
    "description": "The ease-of-use makes this GUI based text editor a top choice for the graphically inclined user. Nothing bad to report.",
    "distro": "Kali GNU/Linux",
    "karma_down": 0,
    "karma_up": 1,
    "locale": "en_US",
    "rating": 100,
    "reported": 0,
    "review_id": 1009,
    "summary": "Simple and easy to use.",
    "user_display": "Sam",
    "user_hash": "7b9eae222c4c2680c1fb0ec5e399735cf7bfbc5e",
    "version": "3.22.0"
  },
  {
    "app_id": "org.gnome.gedit.desktop",
    "date_created": 1468408390,
    "date_deleted": null,
    "description": "It's a great application: clean and intuitive interface and the right balance between ease of use and features. A good number of installable plugins makes it also an adeguate editor for more complex tasks.",
    "distro": "Fedora",
    "karma_down": 0,
    "karma_up": 5,
    "locale": "en_IT",
    "rating": 100,
    "reported": 0,
    "review_id": 475,
    "summary": "Great text editor",
    "user_display": "Alex Stizza",
    "user_hash": "adead34e847f648bf77c0b888dac07b93ad748b0",
    "version": "3.20.2"
  },
  {
    "app_id": "org.gnome.gedit.desktop",
    "date_created": 1467707869,
    "date_deleted": null,
    "description": "When programming I use an IDE. When writing I use a document editor. Gedit is both and neither. It is the handy little swiss army knife with which you can solve simple problems with ease. If I quickly need to open a config file and edit a string I use gedit. If I quickly need to write a note to myself, I use gedit. Gedit starts fast, takes no space and is reliable.",
    "distro": "Arch Linux",
    "karma_down": 0,
    "karma_up": 8,
    "locale": "en_DK",
    "rating": 100,
    "reported": 0,
    "review_id": 374,
    "summary": "A tool for all the quick and small tasks",
    "user_display": "Bastian Ilso",
    "user_hash": "1fe4a5267d81d0697fbad3e0869fbd0ab838f0be",
    "version": "3.20.2"
  },
  {
    "app_id": "org.gnome.gedit.desktop",
    "date_created": 1463001744,
    "date_deleted": null,
    "description": "I use it as my main programming text editor. It's simple, but also surprisingly powerful. Syntax highlighting, spellchecking, regex search and replace? Yes please. And unlike many other GNOME apps, it's extremely rare that I find bugs in gedit. This thing is one of the most stable apps I've ever used.",
    "distro": "Fedora",
    "karma_down": 0,
    "karma_up": 9,
    "locale": "en_US",
    "rating": 100,
    "reported": 0,
    "review_id": 86,
    "summary": "One of the best GNOME apps",
    "user_display": "Michael Catanzaro",
    "user_hash": "1277a625ae6629987ddb7f7f3fd50e232b839284",
    "version": "2:3.20.1"
  },
  {
    "app_id": "org.gnome.gedit.desktop",
    "date_created": 1461772858,
    "date_deleted": null,
    "description": "GEdit integrates really well into the GNOME desktop, and it is perfect for small plain-text editing tasks.\r\nUnfortunately it falls short as a text-editor for programming languages, where it often fails to indent code correctly, sometimes tries to spellcheck code, which makes no sense etc.\r\nSo, for small plaintext-editing tasks, it's a great tool, for programming not so much, because many features which would make GEdit a great programmers text-editor are sacrificed for the simplicity of the \"I just want to write a plaintext file\" usecase - which IMHO happens rarely to the non-technical user.\r\nWithout plugins, GEdit isn't as great as it could be (but fortunately, there are plugins!).",
    "distro": "Debian GNU/Linux",
    "karma_down": 0,
    "karma_up": 7,
    "locale": "en_DE",
    "rating": 60,
    "reported": 0,
    "review_id": 50,
    "summary": "Nice UI, but unclear scope",
    "user_display": "Matthias Klumpp",
    "user_hash": "2e7728c9ec496ec63353c58b420300e0cd458ec3",
    "version": "3.20.1"
  },
  {
    "app_id": "org.gnome.gedit.desktop",
    "date_created": 1460493973,
    "date_deleted": null,
    "description": "A good starting editor that can edit plain text or configuration files but also write code. It comes with a lot of useful extensions",
    "distro": "Fedora",
    "karma_down": 1,
    "karma_up": 9,
    "locale": "en_FR",
    "rating": 80,
    "reported": 0,
    "review_id": 24,
    "summary": "Good versatile editor",
    "user_display": "Baptiste Mille-Mathias",
    "user_hash": "b6d52fb6e71b1abd9307214b6fdb8f5c90298052",
    "version": "2:3.20.1"
  },
  {
    "app_id": "org.gnome.gedit.desktop",
    "date_created": 1457026358,
    "date_deleted": null,
    "description": "For serious work use Pluma from the old 'feature-complete' gnome 2 days. ",
    "distro": "Unknown",
    "karma_down": 5,
    "karma_up": 0,
    "locale": "C",
    "rating": 20,
    "reported": 0,
    "review_id": 9,
    "summary": "Basic app, not too comfy for serious work",
    "user_display": "tux",
    "user_hash": "ab62ab01969a0b969111ac94f22e188b946de425",
    "version": "master"
  },
  {
    "app_id": "org.gnome.gedit.desktop",
    "date_created": 1455272917,
    "date_deleted": null,
    "description": "Straight forward and using minimal chrome to not get in my way.",
    "distro": "GNOME-Continuous",
    "karma_down": 1,
    "karma_up": 16,
    "locale": "en_US",
    "rating": 100,
    "reported": 0,
    "review_id": 5,
    "summary": "Excellent text editor",
    "user_display": "Jakub Steiner",
    "user_hash": "be602646b02bc5b789b7391f2ad061f07674229f",
    "version": "unknown"
  },
  {
    "app_id": "org.gnome.Builder.desktop",
    "date_created": 1478072018,
    "date_deleted": null,
    "description": "Great IDE to develop with a lot of languages, a pity groovy is not yet supported, but the app is young, it has to grow.\nIt cames with VIM modes out of the box (... what more can I say...) \nHighly customizable, lots of settings to help you programming, clean and nice design, a sweet app!",
    "distro": "Debian GNU/Linux",
    "karma_down": 0,
    "karma_up": 1,
    "locale": "en_US",
    "rating": 80,
    "reported": 0,
    "review_id": 931,
    "summary": "Top IDE, flies like an editor, sting like an IDE ",
    "user_display": "amr",
    "user_hash": "ac0c57e5024adbd5aa4f69217f2bd3c890adb656",
    "version": "3.22.1"
  },
  {
    "app_id": "org.gnome.Builder.desktop",
    "date_created": 1477590927,
    "date_deleted": null,
    "description": "Love it. Maybe, add some support for automatically adding files to Makefile.am",
    "distro": "Debian GNU/Linux",
    "karma_down": 0,
    "karma_up": 2,
    "locale": "en_PL",
    "rating": 100,
    "reported": 0,
    "review_id": 880,
    "summary": "Very good",
    "user_display": "Jakub Kaszycki",
    "user_hash": "f114e9e3a64a17ed6d9b1d4c4e997e7f2f58abd9",
    "version": "3.22.1"
  },
];
