import { App } from './app.model';

export const POPULARAPPS: App[] = [
  {
    flatpakAppId: "com.spotify.Client",
    name: "Spotify",
    summary: "Online music streaming service",
    description: '',
    projectLicense: '',
    "iconDesktopUrl": "https://lh3.googleusercontent.com/UrY7BAZ-XfXGpfkeWg0zCCeo-7ras4DCoRalC_WXXWTK9q5b0Iw7B0YQMsVxZaNB7DM=w128",
    "iconMobileUrl": "https://lh3.googleusercontent.com/UrY7BAZ-XfXGpfkeWg0zCCeo-7ras4DCoRalC_WXXWTK9q5b0Iw7B0YQMsVxZaNB7DM=w128",
    homepageUrl: '',
    bugtrackerUrl: '',
    downloadFlatpakRefUrl: '',
    currentReleaseVersion: '',
    currentReleaseDate: null,
    currentReleaseDescription: '',
    inStoreSinceDate: null,
    screenshots: []
  },
  {
    flatpakAppId: "com.skype.Client",
    name: "Skype",
    summary: "Call and message skype users, with video chat support",
    description: '',
    projectLicense: '',
    iconDesktopUrl: "https://lh3.googleusercontent.com/QfAEt_ya6-n8w_TD9-PsghFC2DMSO7fLGNZB4cQ3RtbBbHFkXJE_gxOc3l32-j6LXg=w128",
    iconMobileUrl: "https://lh3.googleusercontent.com/QfAEt_ya6-n8w_TD9-PsghFC2DMSO7fLGNZB4cQ3RtbBbHFkXJE_gxOc3l32-j6LXg=w128",
    homepageUrl: '',
    bugtrackerUrl: '',
    downloadFlatpakRefUrl: '',
    currentReleaseVersion: '',
    currentReleaseDate: null,
    currentReleaseDescription: '',
    inStoreSinceDate: null,
    screenshots: []
  },
  {
    flatpakAppId: "com.discordapp.Discord",
    name: "Discord",
    summary: "Chat client",
    description: '',
    projectLicense: '',
    iconDesktopUrl: "https://lh3.googleusercontent.com/_4zBNFjA8S9yjNB_ONwqBvxTvyXYdC7Nh1jYZ2x6YEcldBr2fyijdjM2J5EoVdTpnkA=w256",
    iconMobileUrl: "https://lh3.googleusercontent.com/_4zBNFjA8S9yjNB_ONwqBvxTvyXYdC7Nh1jYZ2x6YEcldBr2fyijdjM2J5EoVdTpnkA=w256",
    homepageUrl: '',
    bugtrackerUrl: '',
    downloadFlatpakRefUrl: '',
    currentReleaseVersion: '',
    currentReleaseDate: null,
    currentReleaseDescription: '',
    inStoreSinceDate: null,
    screenshots: []
  },
  {
    flatpakAppId: "com.valvesoftware.Steam",
    name: "Steam",
    summary: "Manage and play games distributed by Steam",
    description: '',
    projectLicense: '',
    iconDesktopUrl: "/repo/appstream/x86_64/icons/128x128/com.valvesoftware.Steam.png",
    iconMobileUrl: "/repo/appstream/x86_64/icons/64x64/com.valvesoftware.Steam.png",
    homepageUrl: '',
    bugtrackerUrl: '',
    downloadFlatpakRefUrl: '',
    currentReleaseVersion: '',
    currentReleaseDate: null,
    currentReleaseDescription: '',
    inStoreSinceDate: null,
    screenshots: []
  },
  {
    flatpakAppId: "org.libretro.RetroArch",
    name: "RetroArch",
    summary: "Frontend for emulators, game engines and media players.",
    description: '',
    projectLicense: '',
    iconDesktopUrl: "/repo/appstream/x86_64/icons/128x128/org.libretro.RetroArch.png",
    iconMobileUrl: "/repo/appstream/x86_64/icons/64x64/org.libretro.RetroArch.png",
    homepageUrl: '',
    bugtrackerUrl: '',
    downloadFlatpakRefUrl: '',
    currentReleaseVersion: '',
    currentReleaseDate: null,
    currentReleaseDescription: '',
    inStoreSinceDate: null,
    screenshots: []
  },
  {
    flatpakAppId: "de.haeckerfelix.gradio",
    name: "Gradio",
    summary: "Find and listen to internet radio stations",
    description: '',
    projectLicense: '',
    iconDesktopUrl: "/repo/appstream/x86_64/icons/128x128/de.haeckerfelix.gradio.png",
    iconMobileUrl: "/repo/appstream/x86_64/icons/64x64/de.haeckerfelix.gradio.png",
    homepageUrl: '',
    bugtrackerUrl: '',
    downloadFlatpakRefUrl: '',
    currentReleaseVersion: '',
    currentReleaseDate: null,
    currentReleaseDescription: '',
    inStoreSinceDate: null,
    screenshots: []
  },
  {
    "flatpakAppId": "org.telegram.desktop",
    "name": "Telegram Desktop",
    "summary": "Telegram Desktop messenger",
    description: '',
    projectLicense: '',
    "iconDesktopUrl": "/repo/appstream/x86_64/icons/128x128/org.telegram.desktop.png",
    "iconMobileUrl": "/repo/appstream/x86_64/icons/64x64/org.telegram.desktop.png",
    homepageUrl: '',
    bugtrackerUrl: '',
    downloadFlatpakRefUrl: '',
    currentReleaseVersion: '',
    currentReleaseDate: null,
    currentReleaseDescription: '',
    inStoreSinceDate: null,
    screenshots: []
  },
  {
    flatpakAppId: "com.github.wwmm.pulseeffects",
    name: "PulseEffects",
    summary: "Audio Effects for PulseAudio Applications",
    description: '',
    projectLicense: '',
    iconDesktopUrl: "/repo/appstream/x86_64/icons/128x128/com.github.wwmm.pulseeffects.png",
    iconMobileUrl: "/repo/appstream/x86_64/icons/64x64/com.github.wwmm.pulseeffects.png",
    homepageUrl: '',
    bugtrackerUrl: '',
    downloadFlatpakRefUrl: '',
    currentReleaseVersion: '',
    currentReleaseDate: null,
    currentReleaseDescription: '',
    inStoreSinceDate: null,
    screenshots: []
  },
];
